services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    command: ["--bind_ip_all"]

  frontend:
    build:
      context: ./fabsa-frontend
    environment:
      - BACKEND_API_URL=http://backend:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./fabsa-backend
    networks:
      - app-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongo:27017/FABSA?authSource=admin
      - PYTHON_API_URL=http://python-model:8000
    depends_on:
      - mongo
      - python-model

  python-model:
    build:
      context: ./fabsa-model
    networks:
      - app-network

networks:
  app-network:
    driver: bridge